// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {TestBase} from "../TestBase.sol";
import {HashSig} from "../../src/libs/HashSig.sol";
import {SdkVectors, SdkVector} from "../vectors/HashSigVectors.data.sol";

/// Cross-language replay: every signature was generated by the TypeScript SDK
/// (sdk/test/vectors.gen.ts). Forge must reconstruct the SAME expectedLeaf and
/// SAME tree root from the SDK's digest + wots + path — proving byte-for-byte
/// agreement between sdk/src/*.ts and contracts/src/libs/HashSig.sol.
///
/// The generated struct stores `wots`/`path` as fixed-size arrays (literal
/// sizes), so they are copied into dynamic arrays before calling the library —
/// fixed-size arrays cannot name `HashSig.LEN`/`HashSig.TREE_H` as a type size.
contract HashSigVectorsTest is TestBase {
    function test_sdk_vectors_verify() public {
        SdkVector[] memory vs = SdkVectors.all();
        assertTrue(vs.length >= 5, "expected >=5 vectors");
        for (uint256 i = 0; i < vs.length; ++i) {
            SdkVector memory v = vs[i];
            bytes32 leaf = HashSig.leafFromSignature(v.digest, _wotsOf(v));
            assertEq(leaf, v.expectedLeaf, string.concat("leaf mismatch @", _uint2str(i)));

            bytes32 root = HashSig.computeRoot(leaf, uint256(v.leafIndex), _pathOf(v));
            assertEq(root, v.root, string.concat("root mismatch @", _uint2str(i)));
        }
    }

    function test_sdk_vectors_reject_tamperedDigest() public {
        SdkVector[] memory vs = SdkVectors.all();
        for (uint256 i = 0; i < vs.length; ++i) {
            SdkVector memory v = vs[i];
            // Same signature over a different digest must NOT open the same leaf.
            bytes32 other = keccak256(abi.encodePacked(v.digest, "tampered"));
            if (other == v.digest) continue;
            bytes32 leaf = HashSig.leafFromSignature(other, _wotsOf(v));
            assertTrue(leaf != v.expectedLeaf, string.concat("tamper accepted @", _uint2str(i)));
        }
    }

    function test_sdk_vectors_reject_leafShift() public {
        SdkVector[] memory vs = SdkVectors.all();
        for (uint256 i = 1; i < vs.length; ++i) {
            SdkVector memory v = vs[i];
            // Path of vector i replayed at a different leafIndex must not verify.
            bytes32 leaf = HashSig.leafFromSignature(v.digest, _wotsOf(v));
            uint256 shifted = uint256(v.leafIndex) ^ 1;
            bytes32 root = HashSig.computeRoot(leaf, shifted, _pathOf(v));
            if (shifted >= (1 << HashSig.TREE_H)) continue;
            assertTrue(root != v.root || shifted == uint256(v.leafIndex), "leaf shift must break proof");
        }
    }

    // --- helpers --------------------------------------------------------------

    // Fixed -> dynamic copy. HashSig.TREE_N is used only in runtime `new` sizes
    // (legal); it never appears as a fixed-array *type* length (parse error).
    function _wotsOf(SdkVector memory v) internal pure returns (bytes32[] memory out) {
        out = new bytes32[](HashSig.LEN);
        for (uint256 j = 0; j < HashSig.LEN; ++j) out[j] = v.wots[j];
    }

    function _pathOf(SdkVector memory v) internal pure returns (bytes32[] memory out) {
        out = new bytes32[](HashSig.TREE_H);
        for (uint256 j = 0; j < HashSig.TREE_H; ++j) out[j] = v.path[j];
    }

    function _uint2str(uint256 v) internal pure returns (string memory s) {
        if (v == 0) return "0";
        uint256 n = v;
        uint256 len;
        while (n > 0) {
            len++;
            n /= 10;
        }
        bytes memory b = new bytes(len);
        while (v > 0) {
            len--;
            b[len] = bytes1(uint8(48 + (v % 10)));
            v /= 10;
        }
        return string(b);
    }
}
