# syntax=docker/dockerfile:1

FROM node:22-alpine AS dependencies
WORKDIR /app

COPY 0xNothing-zkLTC-Testnet/apps/web/package.json ./package.json
COPY 0xNothing-zkLTC-Testnet/apps/web/package-lock.json ./package-lock.json
RUN npm ci

FROM node:22-alpine AS builder
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

# Railway only exposes service variables to Docker build steps when the
# corresponding ARG is declared. These are public values embedded by Next.js;
# server-only secrets such as PINATA_JWT remain runtime-only.
ARG NEXT_PUBLIC_ALLOW_DEPLOYMENT_OVERRIDES
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_BTC_ORACLE_ADDRESS
ARG NEXT_PUBLIC_DEPLOYMENT_BLOCK
ARG NEXT_PUBLIC_DEX_FACTORY_ADDRESS
ARG NEXT_PUBLIC_DEX_ROUTER_ADDRESS
ARG NEXT_PUBLIC_DIA_BTC_FEED_ADDRESS
ARG NEXT_PUBLIC_DIA_ETH_FEED_ADDRESS
ARG NEXT_PUBLIC_DIA_LTC_FEED_ADDRESS
ARG NEXT_PUBLIC_ETH_ORACLE_ADDRESS
ARG NEXT_PUBLIC_FARM_FACTORY_ADDRESS
ARG NEXT_PUBLIC_GAUGE_FACTORY_ADDRESS
ARG NEXT_PUBLIC_GOLDSKY_ENDPOINT
ARG NEXT_PUBLIC_LEGACY_NBTC_VAULT_ADDRESS
ARG NEXT_PUBLIC_LEGACY_NETH_VAULT_ADDRESS
ARG NEXT_PUBLIC_LENDING_POOL_ADDRESS
ARG NEXT_PUBLIC_LENDING_RISK_ACTIONS_ENABLED
ARG NEXT_PUBLIC_LITVM_EXPLORER_URL
ARG NEXT_PUBLIC_LITVM_RPC_URL
ARG NEXT_PUBLIC_LP_LOCKER_ADDRESS
ARG NEXT_PUBLIC_LTC_ORACLE_ADDRESS
ARG NEXT_PUBLIC_NBTC_ADDRESS
ARG NEXT_PUBLIC_NBTC_NUSD_GAUGE_ADDRESS
ARG NEXT_PUBLIC_NBTC_NUSD_PAIR_ADDRESS
ARG NEXT_PUBLIC_NBTC_VAULT_ADDRESS
ARG NEXT_PUBLIC_NETH_ADDRESS
ARG NEXT_PUBLIC_NETH_NUSD_GAUGE_ADDRESS
ARG NEXT_PUBLIC_NETH_NUSD_PAIR_ADDRESS
ARG NEXT_PUBLIC_NETH_VAULT_ADDRESS
ARG NEXT_PUBLIC_NUSD_ADDRESS
ARG NEXT_PUBLIC_PUMP_ADDRESS
ARG NEXT_PUBLIC_PUMP_GRADUATION_ADAPTER_ADDRESS
ARG NEXT_PUBLIC_PUMP_GRADUATION_CONTROLLER_ADDRESS
ARG NEXT_PUBLIC_SYNTH_FEE_GAUGE_FACTORY_ADDRESS
ARG NEXT_PUBLIC_SYNTH_RISK_ACTIONS_ENABLED
ARG NEXT_PUBLIC_SYNTH_SAFETY_RESERVE_ADDRESS
ARG NEXT_PUBLIC_TOKEN_METADATA_REGISTRY_ADDRESS
ARG NEXT_PUBLIC_WZKLTC_ADDRESS
ARG NEXT_PUBLIC_WZKLTC_NUSD_GAUGE_ADDRESS
ARG NEXT_PUBLIC_WZKLTC_NUSD_PAIR_ADDRESS

COPY --from=dependencies /app/node_modules ./node_modules
COPY 0xNothing-zkLTC-Testnet/apps/web/ ./
RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOSTNAME=0.0.0.0

COPY --from=builder /app/public ./public
COPY --from=builder --chown=node:node /app/.next/standalone ./
COPY --from=builder --chown=node:node /app/.next/static ./.next/static

USER node
EXPOSE 3000

# Next's standalone server reads Railway's injected PORT automatically.
CMD ["node", "server.js"]
