[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
cache_path = "cache"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./deployments" }]
solc_version = "0.8.24"
evm_version = "paris"
optimizer = true
optimizer_runs = 20000
fuzz = { runs = 512 }
invariant = { runs = 128, depth = 64, fail_on_revert = false }

remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
quote_style = "double"
number_underscore = "thousands"
