import { type Address, bytesToHex, type Hex, isAddress } from "viem";
import { type HDAccount, mnemonicToAccount, type PrivateKeyAccount, privateKeyToAccount } from "viem/accounts";
import { DEFAULT_LOCALE, isLocaleCode, type LocaleCode, t } from "../i18n";
import {
  LITVM_NETWORK,
  normalizeCustomNetworks,
  resolveNetwork,
  type WalletNetwork,
} from "../../config/networks";
import { persistentStore, sessionStore } from "../platform/storage";
import { STORAGE_KEYS } from "../platform/storageKeys";
import { withNamedLock } from "../platform/locks";
import {
  decryptWithKey,
  type EncryptedBlob,
  encryptJson,
  exportKey,
  importKey,
  keyForBlob,
} from "./crypto";
import { checkMnemonic, newMnemonic } from "./mnemonic";

/**
 * The keyring.
 *
 * On disk there is exactly one secret: an AES-GCM blob over
 * `{ mnemonic, imported[] }`. Everything else — addresses, labels, which
 * account is active — is public metadata kept in the clear so the UI can render
 * a locked wallet without touching key material.
 *
 * While unlocked, the *derived AES key* (not the password, not the mnemonic)
 * lives in session storage: chrome.storage.session on the extension, a plain
 * in-process Map on Android. Both are memory-only. Any read of the secret
 * re-decrypts the blob, so locking is a single delete with nothing left behind.
 */

export interface VaultSecret {
  mnemonic: string;
  /** Keys imported outside the HD tree. */
  imported: Hex[];
}

export const MIN_WALLET_PASSWORD_LENGTH = 8;
const PRIVATE_KEY = /^0x[0-9a-fA-F]{64}$/u;

function isVaultSecret(value: unknown): value is VaultSecret {
  if (value === null || typeof value !== "object" || Array.isArray(value)) return false;
  const secret = value as Partial<VaultSecret>;
  return typeof secret.mnemonic === "string"
    && secret.mnemonic.length > 0
    && secret.mnemonic.length <= 1_024
    && Array.isArray(secret.imported)
    && secret.imported.length <= 10_000
    && secret.imported.every((key) => typeof key === "string" && PRIVATE_KEY.test(key));
}

function assertNewPassword(password: string): void {
  if (password.length < MIN_WALLET_PASSWORD_LENGTH) {
    throw new Error(t("onb.shortPassword", { min: MIN_WALLET_PASSWORD_LENGTH }));
  }
}

export interface AccountMeta {
  address: Address;
  /**
   * The name the user typed, or "" for a never-renamed account — those are named
   * at display time by `accountLabel` so the default follows the UI language.
   */
  label: string;
  source: "hd" | "imported";
  /** HD address index, or the position in `imported` for imported keys. */
  index: number;
}

/**
 * Default names generated by builds that stored them in Vietnamese. Treated as
 * "never renamed" so an upgrade re-labels them in the chosen language instead of
 * leaving one screen in the old one.
 */
const LEGACY_DEFAULT_LABEL = /^(?:Ví Chính|Ví \d+|Nhập \d+)$/u;

/** What the UI shows for an account: the custom name, or a localised default. */
export function accountLabel(meta: AccountMeta): string {
  const custom = meta.label.trim();
  if (custom.length > 0 && !LEGACY_DEFAULT_LABEL.test(custom)) return custom;
  if (meta.source === "imported") return t("account.importedN", { n: meta.index + 1 });
  return meta.index === 0 ? t("account.main") : t("account.hdN", { n: meta.index + 1 });
}

export interface AccountsState {
  accounts: AccountMeta[];
  active: Address | null;
}

export interface WalletSettings {
  autoLockMinutes: number;
  slippageBps: number;
  /** UI language. English by default in every fresh install. */
  locale: LocaleCode;
  /** Background mode. Dark is the safe default for an existing install. */
  theme: WalletTheme;
  /** Selected built-in or locally configured EVM network. */
  networkId: string;
  /** RPC profiles entered by the user; never contains key material. */
  customNetworks: WalletNetwork[];
}

export type WalletTheme = "dark" | "light";

export const DEFAULT_SETTINGS: WalletSettings = {
  autoLockMinutes: 15,
  slippageBps: 50,
  locale: DEFAULT_LOCALE,
  theme: "dark",
  networkId: LITVM_NETWORK.id,
  customNetworks: [],
};

export class WalletLockedError extends Error {
  constructor() {
    super(t("vault.locked"));
    this.name = "WalletLockedError";
  }
}

export class WrongPasswordError extends Error {
  constructor() {
    super(t("vault.wrongPassword"));
    this.name = "WrongPasswordError";
  }
}

interface SessionRecord {
  key: string;
  /** Kept optional so sessions written by v1 can be read and migrated safely. */
  expiresAt?: number;
}

const SESSION_LOCK = "session";
const SETTINGS_LOCK = "settings";
const VAULT_LOCK = "vault";
const MAX_ACCOUNTS = 100;
const MAX_HD_INDEX = 100_000;

/* ---------------------------------------------------------------- settings */

export async function readSettings(): Promise<WalletSettings> {
  const stored = await persistentStore.get<Partial<WalletSettings>>(STORAGE_KEYS.settings);
  const merged = { ...DEFAULT_SETTINGS, ...(stored ?? {}) };
  const autoLock = Number(merged.autoLockMinutes);
  merged.autoLockMinutes = Number.isFinite(autoLock) && autoLock > 0 && autoLock <= 24 * 60
    ? Math.round(autoLock)
    : DEFAULT_SETTINGS.autoLockMinutes;
  const slippage = Number(merged.slippageBps);
  merged.slippageBps = Number.isFinite(slippage) && slippage >= 0 && slippage <= 5_000
    ? Math.round(slippage)
    : DEFAULT_SETTINGS.slippageBps;
  // A locale written by an older or hand-edited build must not reach the catalog.
  if (!isLocaleCode(merged.locale)) merged.locale = DEFAULT_LOCALE;
  if (merged.theme !== "light" && merged.theme !== "dark") merged.theme = DEFAULT_SETTINGS.theme;
  merged.customNetworks = normalizeCustomNetworks(merged.customNetworks);
  merged.networkId = resolveNetwork(merged.networkId, merged.customNetworks).id;
  return merged;
}

export async function writeSettings(patch: Partial<WalletSettings>): Promise<WalletSettings> {
  return withNamedLock(SETTINGS_LOCK, async () => {
    const next = { ...(await readSettings()), ...patch };
    next.customNetworks = normalizeCustomNetworks(next.customNetworks);
    next.networkId = resolveNetwork(next.networkId, next.customNetworks).id;
    await persistentStore.set(STORAGE_KEYS.settings, next);
    return next;
  });
}

/* ------------------------------------------------------------------- vault */

async function readVaultBlob(): Promise<EncryptedBlob | null> {
  return persistentStore.get<EncryptedBlob>(STORAGE_KEYS.vault);
}

export async function hasVault(): Promise<boolean> {
  return (await readVaultBlob()) !== null;
}

async function putSession(key: CryptoKey): Promise<void> {
  await withNamedLock(SESSION_LOCK, async () => {
    const { autoLockMinutes } = await readSettings();
    await sessionStore.setMany([
      [STORAGE_KEYS.session, { key: await exportKey(key) } satisfies SessionRecord],
      [STORAGE_KEYS.sessionDeadline, Date.now() + autoLockMinutes * 60_000],
    ]);
  });
}

async function sessionKey(): Promise<CryptoKey | null> {
  return withNamedLock(SESSION_LOCK, async () => {
    const [record, storedDeadline] = await Promise.all([
      sessionStore.get<SessionRecord>(STORAGE_KEYS.session),
      sessionStore.get<number>(STORAGE_KEYS.sessionDeadline),
    ]);
    if (!record) return null;
    const deadline = storedDeadline ?? record.expiresAt ?? 0;
    if (deadline <= Date.now()) {
      await Promise.all([
        sessionStore.remove(STORAGE_KEYS.session),
        sessionStore.remove(STORAGE_KEYS.sessionDeadline),
      ]);
      return null;
    }
    try {
      return await importKey(record.key);
    } catch {
      await Promise.all([
        sessionStore.remove(STORAGE_KEYS.session),
        sessionStore.remove(STORAGE_KEYS.sessionDeadline),
      ]);
      return null;
    }
  });
}

export async function isUnlocked(): Promise<boolean> {
  return (await sessionKey()) !== null;
}

/** Pushes the auto-lock deadline out; called on any deliberate user action. */
export async function touchSession(): Promise<void> {
  await withNamedLock(SESSION_LOCK, async () => {
    const [record, storedDeadline] = await Promise.all([
      sessionStore.get<SessionRecord>(STORAGE_KEYS.session),
      sessionStore.get<number>(STORAGE_KEYS.sessionDeadline),
    ]);
    const deadline = storedDeadline ?? record?.expiresAt ?? 0;
    if (!record || deadline <= Date.now()) return;
    const { autoLockMinutes } = await readSettings();
    // Only the deadline is written. A stale activity task can therefore never
    // put an AES key back after lock() removed it.
    await sessionStore.set(
      STORAGE_KEYS.sessionDeadline,
      Date.now() + autoLockMinutes * 60_000,
    );
  });
}

export async function lock(): Promise<void> {
  await withNamedLock(SESSION_LOCK, async () => {
    await Promise.all([
      sessionStore.remove(STORAGE_KEYS.session),
      sessionStore.remove(STORAGE_KEYS.sessionDeadline),
    ]);
  });
}

export async function getSecret(): Promise<VaultSecret> {
  const [key, blob] = await Promise.all([sessionKey(), readVaultBlob()]);
  if (!key || !blob) throw new WalletLockedError();
  try {
    const secret = await decryptWithKey<unknown>(blob, key);
    if (!isVaultSecret(secret)) throw new Error("Invalid vault secret");
    return secret;
  } catch {
    // A session key that no longer opens the vault is stale (password change in
    // another window); treat it as locked rather than as a corrupt vault.
    await lock();
    throw new WalletLockedError();
  }
}

async function unlockUnderVaultLock(password: string): Promise<VaultSecret> {
  const blob = await readVaultBlob();
  if (!blob) throw new WalletLockedError();
  let key: CryptoKey;
  let secret: VaultSecret;
  try {
    key = await keyForBlob(blob, password);
    const decrypted = await decryptWithKey<unknown>(blob, key);
    if (!isVaultSecret(decrypted)) throw new Error("Invalid vault secret");
    secret = decrypted;
  } catch {
    throw new WrongPasswordError();
  }
  await putSession(key);
  return secret;
}

export function unlock(password: string): Promise<VaultSecret> {
  return withNamedLock(VAULT_LOCK, () => unlockUnderVaultLock(password));
}

/* ---------------------------------------------------------------- accounts */

export async function readAccounts(): Promise<AccountsState> {
  const raw = await persistentStore.get<unknown>(STORAGE_KEYS.accounts);
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
    return { accounts: [], active: null };
  }
  const value = raw as Record<string, unknown>;
  const source = Array.isArray(value.accounts) ? value.accounts.slice(0, MAX_ACCOUNTS) : [];
  const accounts: AccountMeta[] = [];
  const seen = new Set<string>();
  for (const candidate of source) {
    if (candidate === null || typeof candidate !== "object" || Array.isArray(candidate)) continue;
    const entry = candidate as Record<string, unknown>;
    const candidateAddress = entry.address;
    if (typeof candidateAddress !== "string" || !isAddress(candidateAddress)) continue;
    if (entry.source !== "hd" && entry.source !== "imported") continue;
    const index = Number(entry.index);
    if (
      !Number.isSafeInteger(index)
      || index < 0
      || index > (entry.source === "hd" ? MAX_HD_INDEX : 10_000)
    ) continue;
    const key = candidateAddress.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    const label = typeof entry.label === "string"
      && entry.label.length <= 24
      && !/[\u0000-\u001f\u007f]/u.test(entry.label)
      ? entry.label
      : "";
    accounts.push({ address: candidateAddress, label, source: entry.source, index });
  }
  const rawActive = value.active;
  const active = typeof rawActive === "string"
    ? accounts.find((entry) => entry.address.toLowerCase() === rawActive.toLowerCase())?.address
      ?? null
    : null;
  return { accounts, active };
}

async function writeAccounts(state: AccountsState): Promise<AccountsState> {
  await persistentStore.set(STORAGE_KEYS.accounts, state);
  return state;
}

function hdMeta(mnemonic: string, index: number, label?: string): AccountMeta {
  return {
    address: mnemonicToAccount(mnemonic, { addressIndex: index }).address,
    // No default text on disk: `accountLabel` names it in the current language.
    label: label ?? "",
    source: "hd",
    index,
  };
}

/* ------------------------------------------------------------ create/import */

export interface CreateVaultResult {
  mnemonic: string;
  accounts: AccountsState;
}

/**
 * Creates the vault and unlocks it. `phrase` is optional: onboarding generates a
 * fresh 12-word phrase, the import flow passes the user's own. Refuses to run if
 * a vault already exists — overwriting one would destroy funds.
 */
export async function createVault(
  password: string,
  phrase?: string,
): Promise<CreateVaultResult> {
  return withNamedLock(VAULT_LOCK, async () => {
    if (await hasVault()) throw new Error(t("vault.exists"));
    assertNewPassword(password);
    const checked = await checkMnemonic(phrase ?? newMnemonic());
    if (!checked.ok) {
      throw new Error(t("vault.badPhrase", { reason: t(`mnemonic.${checked.reason}`) }));
    }

    const secret: VaultSecret = { mnemonic: checked.phrase, imported: [] };
    const blob = await encryptJson(secret, password);
    const first = hdMeta(secret.mnemonic, 0);
    const accounts = { accounts: [first], active: first.address } satisfies AccountsState;
    await persistentStore.setMany([
      [STORAGE_KEYS.vault, blob],
      [STORAGE_KEYS.accounts, accounts],
    ]);
    await putSession(await keyForBlob(blob, password));
    return { mnemonic: secret.mnemonic, accounts };
  });
}

export async function addHdAccount(label?: string): Promise<AccountsState> {
  return withNamedLock(VAULT_LOCK, async () => {
    const secret = await getSecret();
    const state = await readAccounts();
    if (state.accounts.length >= MAX_ACCOUNTS) {
      throw new Error(`This wallet supports up to ${MAX_ACCOUNTS} accounts`);
    }
    const nextIndex = state.accounts.reduce(
      (max, meta) => (meta.source === "hd" ? Math.max(max, meta.index + 1) : max),
      0,
    );
    const meta = hdMeta(secret.mnemonic, nextIndex, label);
    if (state.accounts.some((existing) => existing.address === meta.address)) return state;
    return writeAccounts({ accounts: [...state.accounts, meta], active: meta.address });
  });
}

/** Adds a raw private key. Requires the password: it rewrites the vault blob. */
export async function importPrivateKey(
  password: string,
  privateKey: Hex,
  label?: string,
): Promise<AccountsState> {
  return withNamedLock(VAULT_LOCK, async () => {
    const secret = await unlockUnderVaultLock(password);
    const account = privateKeyToAccount(privateKey);
    const state = await readAccounts();
    if (state.accounts.some((existing) => existing.address === account.address)) {
      return writeAccounts({ ...state, active: account.address });
    }
    if (state.accounts.length >= MAX_ACCOUNTS) {
      throw new Error(`This wallet supports up to ${MAX_ACCOUNTS} accounts`);
    }
    const imported = [...secret.imported, privateKey];
    const blob = await encryptJson({ ...secret, imported } satisfies VaultSecret, password);
    const meta: AccountMeta = {
      address: account.address,
      label: label ?? "",
      source: "imported",
      index: imported.length - 1,
    };
    const accounts = { accounts: [...state.accounts, meta], active: meta.address };
    await persistentStore.setMany([
      [STORAGE_KEYS.vault, blob],
      [STORAGE_KEYS.accounts, accounts],
    ]);
    await putSession(await keyForBlob(blob, password));
    return accounts;
  });
}

export async function setActiveAccount(address: Address): Promise<AccountsState> {
  return withNamedLock(VAULT_LOCK, async () => {
    const state = await readAccounts();
    if (!state.accounts.some((meta) => meta.address === address)) return state;
    return writeAccounts({ ...state, active: address });
  });
}

export async function renameAccount(address: Address, label: string): Promise<AccountsState> {
  return withNamedLock(VAULT_LOCK, async () => {
    const state = await readAccounts();
    return writeAccounts({
      ...state,
      accounts: state.accounts.map((meta) => (meta.address === address ? { ...meta, label } : meta)),
    });
  });
}

/* ----------------------------------------------------------------- signing */

/**
 * Returns a viem account able to sign. Built on demand from the decrypted
 * secret and never cached, so a lock takes effect immediately everywhere.
 */
export async function signerFor(address: Address): Promise<HDAccount | PrivateKeyAccount> {
  const [secret, state] = await Promise.all([getSecret(), readAccounts()]);
  const meta = state.accounts.find(
    (candidate) => candidate.address.toLowerCase() === address.toLowerCase(),
  );
  if (!meta) throw new Error(t("vault.noAccount", { address }));
  if (meta.source === "hd") return mnemonicToAccount(secret.mnemonic, { addressIndex: meta.index });
  const key = secret.imported[meta.index];
  if (!key) throw new Error(t("vault.noKey", { address }));
  return privateKeyToAccount(key);
}

/* -------------------------------------------------------- reveal / rotate */

/** Password re-entry is required to show a secret, even while unlocked. */
export async function revealMnemonic(password: string): Promise<string> {
  return (await unlock(password)).mnemonic;
}

export async function revealPrivateKey(password: string, address: Address): Promise<Hex> {
  const secret = await unlock(password);
  const state = await readAccounts();
  const meta = state.accounts.find(
    (candidate) => candidate.address.toLowerCase() === address.toLowerCase(),
  );
  if (!meta) throw new Error(t("vault.noAccount", { address }));
  if (meta.source === "imported") {
    const key = secret.imported[meta.index];
    if (!key) throw new Error(t("vault.noKey", { address }));
    return key;
  }
  const hdKey = mnemonicToAccount(secret.mnemonic, { addressIndex: meta.index }).getHdKey();
  if (!hdKey.privateKey) throw new Error(t("vault.keyUnreadable"));
  return bytesToHex(hdKey.privateKey);
}

export async function changePassword(current: string, next: string): Promise<void> {
  await withNamedLock(VAULT_LOCK, async () => {
    assertNewPassword(next);
    const secret = await unlockUnderVaultLock(current);
    const blob = await encryptJson(secret, next);
    await persistentStore.set(STORAGE_KEYS.vault, blob);
    await putSession(await keyForBlob(blob, next));
  });
}

/**
 * Destroys the wallet. Only the seed phrase can bring it back, which is why the
 * UI gates this behind an explicit typed confirmation.
 */
export async function wipeWallet(): Promise<void> {
  await withNamedLock(VAULT_LOCK, async () => {
    await lock();
    await Promise.all([
      persistentStore.remove(STORAGE_KEYS.vault),
      persistentStore.remove(STORAGE_KEYS.accounts),
      persistentStore.remove(STORAGE_KEYS.tokens),
      persistentStore.remove(STORAGE_KEYS.history),
      persistentStore.remove(STORAGE_KEYS.snapshots),
      persistentStore.remove(STORAGE_KEYS.connections),
      persistentStore.remove(STORAGE_KEYS.pending),
      persistentStore.remove(STORAGE_KEYS.resolved),
    ]);
  });
}
