import { chromium,expect } from '@playwright/test';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({headless:true}),errors=[],base='http://localhost:3300/DOGEOSxPIXEL';
const page=await browser.newPage({viewport:{width:1440,height:1000}});
page.on('pageerror',e=>errors.push(e.message));
await page.goto(base);await page.locator('.art-card').first().waitFor({timeout:60000});
await page.screenshot({path:'output/desktop-home.png',fullPage:true});
assert.equal(await page.locator('h1').innerText(),'Much pixel.\nVery yours.');
await page.getByRole('link',{name:'Explore',exact:true}).click();await page.locator('.art-card').first().waitFor();
await page.getByRole('button',{name:'For sale',exact:true}).click();await page.waitForTimeout(1000);
await page.screenshot({path:'output/desktop-market.png',fullPage:true});
await page.getByLabel('Search artwork').fill('Friendly');await page.waitForTimeout(1800);
assert.ok((await page.locator('.art-card').allTextContents()).every(t=>t.includes('Friendly')));
await page.getByLabel('Search artwork').fill('');await page.waitForTimeout(1400);
await page.locator('.art-card').first().click();await page.getByRole('dialog').waitFor();
await page.screenshot({path:'output/desktop-token.png',fullPage:true});await page.getByLabel('Close dialog').click();
await page.getByRole('link',{name:'Pixel studio',exact:true}).click();
await page.getByRole('button',{name:'flower',exact:true}).click();
await page.getByPlaceholder('A name for your tiny masterpiece').fill('Browser-tested Flower');
const painted=await page.locator('.canvas-footer').innerText();assert.ok(!painted.startsWith('0 painted'));
await page.getByLabel('Undo',{exact:true}).click();assert.ok((await page.locator('.canvas-footer').innerText()).startsWith('0 painted'));
await page.getByLabel('Redo',{exact:true}).click();
await page.getByLabel('Canvas size').selectOption('16');
await page.screenshot({path:'output/desktop-studio.png',fullPage:true});
await page.getByRole('button',{name:'Mint your pixel',exact:false}).click();assert.ok(await page.getByRole('dialog').isVisible());
await page.getByLabel('Close dialog').click();
await page.reload();await expect(page.getByPlaceholder('A name for your tiny masterpiece')).toHaveValue('Browser-tested Flower');
await page.getByRole('link',{name:'Collections',exact:true}).click();await page.locator('.collection-card').first().waitFor();await page.screenshot({path:'output/desktop-collections.png',fullPage:true});
const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});mobile.on('pageerror',e=>errors.push(e.message));
for(const path of ['','/market','/studio','/collections','/wallet','/activity']) {await mobile.goto(base+path);await mobile.waitForTimeout(1800);assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Mobile overflow '+path);await mobile.screenshot({path:'output/mobile-'+(path.slice(1)||'home')+'.png',fullPage:true});}
assert.deepEqual(errors,[]);await writeFile('output/browser-smoke.json',JSON.stringify({passed:true,errors,checks:['desktop home','market filter/search','artwork modal','studio template/undo/redo/resize','draft restoration','disconnected mint','collections','6 mobile routes without overflow'],finished:new Date().toISOString()},null,2));await browser.close();console.log('Browser smoke passed. Screenshots saved in output/.');
