import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import deployment from '../src/generated/deployment.json' with {type:'json'};
// Execute actual mapping sources against a lightweight entity store. This checks
// event ordering and accounting; graph build separately checks AssemblyScript/WASM.
function harness() {
 const store=new Map();
 class Int {constructor(value){this.value=BigInt(value);}static zero(){return new Int(0);}static fromI32(n){return new Int(n);}static fromString(n){return new Int(n);}plus(n){return new Int(this.value+n.value);}minus(n){return new Int(this.value-n.value);}equals(n){return this.value===n.value;}toString(){return String(this.value);}toI32(){return Number(this.value);}}
 class Address {constructor(value){this.value=value.toLowerCase();}static fromString(s){return new Address(s);}static fromBytes(s){return s;}toHexString(){return this.value;}equals(other){return this.value===other.value;}notEqual(other){return !this.equals(other);}}
 const entities={};for(const kind of ['Pixel','Collection','Listing','Offer','Sale','Activity','Account','Stats','MarketApproval']) entities[kind]=class {constructor(id){this.id=id;}static load(id){const saved=store.get(kind+':'+id);return saved?Object.assign(new this(id),saved):null;}save(){store.set(kind+':'+this.id,Object.assign(new this.constructor(this.id),this));}};
 const maker=new Address('0x1111111111111111111111111111111111111111'),buyer=new Address('0x2222222222222222222222222222222222222222');
 const modules={},load=name=>{if(modules[name])return modules[name];const module={exports:{}};modules[name]=module.exports;const code=ts.transpileModule(readFileSync(new URL('../subgraph/src/'+name+'.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const require=key=>key==='@graphprotocol/graph-ts'?{BigInt:Int,Address}:key==='../generated/schema'?entities:key.endsWith('DogeosPixel/DogeosPixel')?{DogeosPixel:{bind:()=>({tokenPackedData:()=>({getArtName:()=> 'Doge',getDescription:()=>'',getGridSize:()=>new Int(8),getPixelData:()=> '0x000000ff0000',getArtworkHash:()=>new Address('0x1234'),getCreator:()=>maker,getMintedAt:()=>new Int(100)})})}}:key.includes('generated/')?{}:load(key.replace('./',''));vm.runInNewContext(code,{module,exports:module.exports,require});return modules[name]=module.exports;};
 const pixel=load('pixel'),market=load('market');let at=0;
 const event=params=>({params,address:maker,transaction:{hash:new Address('0x'+(++at).toString(16).padStart(64,'0')),from:maker},logIndex:new Int(at),block:{number:new Int(at),timestamp:new Int(1000+at)}});
 const n=value=>new Int(value),get=(kind,id)=>store.get(kind+':'+id);
 pixel.handleTransfer(event({tokenId:n(1),from:new Address('0x0000000000000000000000000000000000000000'),to:maker}));pixel.handleMinted(event({tokenId:n(1),creator:maker}));
 return {pixel,market,event,n,maker,buyer,get,store,Address};
}
test('mint metadata and collections survive a secondary-owner transfer',()=>{const h=harness(),{pixel,event,n,maker,buyer,get}=h;pixel.handleCollectionCreated(event({collectionId:n(1),owner:maker,name:'Pack',description:'A story'}));pixel.handleTokenCollectionChanged(event({tokenId:n(1),previousCollection:n(0),collectionId:n(1)}));pixel.handleTransfer(event({tokenId:n(1),from:maker,to:buyer}));assert.equal(get('Collection','1').pixelCount,1);assert.equal(get('Pixel','1').owner,buyer);assert.equal(get('Pixel','1').collection,'1');assert.equal(get('Stats','global').minted.toString(),'1');pixel.handleTokenCollectionChanged(event({tokenId:n(1),previousCollection:n(1),collectionId:n(0)}));assert.equal(get('Collection','1').pixelCount,0);});
test('self-transfer retains approval-for-all listing; real transfer invalidates it',()=>{const {pixel,market,event,n,maker,buyer,get}=harness();market.handleListed(event({tokenId:n(1),listingId:n(1),seller:maker,price:n(10000),expiry:n(2000),nonce:n(1)}));pixel.handleTransfer(event({tokenId:n(1),from:maker,to:maker}));assert.equal(get('Listing','1').status,'ACTIVE');assert.equal(get('Pixel','1').ownershipNonce.toString(),'1');pixel.handleTransfer(event({tokenId:n(1),from:maker,to:buyer}));assert.equal(get('Listing','1').status,'INVALIDATED');assert.equal(get('Pixel','1').listing,null);});
test('sale after Transfer event pays original creator and protocol exactly once',()=>{const {pixel,market,event,n,maker,buyer,get,Address}=harness();market.handleListed(event({tokenId:n(1),listingId:n(1),seller:maker,price:n(10000),expiry:n(2000),nonce:n(1)}));pixel.handleTransfer(event({tokenId:n(1),from:maker,to:buyer}));market.handleSold(event({tokenId:n(1),listingId:n(1),seller:maker,buyer,price:n(10000),royalty:n(100),fee:n(100)}));assert.equal(get('Listing','1').status,'SOLD');assert.equal(get('Account',maker.toHexString()).credits.toString(),'9900');assert.equal(get('Account',deployment.deployer.toLowerCase()).credits.toString(),'100');assert.equal(get('Stats','global').volume.toString(),'10000');market.handleWithdrawn(event({account:maker,recipient:maker,amount:n(9900)}));assert.equal(get('Account',maker.toHexString()).credits.toString(),'0');});
test('replaced listings and cancelled offers retain history and refund credits',()=>{const {market,event,n,maker,buyer,get}=harness();for(let i=1;i<=2;i++)market.handleListed(event({tokenId:n(1),listingId:n(i),seller:maker,price:n(10000),expiry:n(2000),nonce:n(1)}));assert.equal(get('Listing','1').status,'REPLACED');market.handleOfferMade(event({offerId:n(1),tokenId:n(1),bidder:buyer,amount:n(5000),expiry:n(2000)}));market.handleOfferCancelled(event({offerId:n(1)}));assert.equal(get('Offer','1').status,'CANCELLED');assert.equal(get('Account',buyer.toHexString()).credits.toString(),'5000');market.handleListingCancelled(event({tokenId:n(1),listingId:n(2)}));assert.equal(get('Pixel','1').listing,null);});
test('accepted offer is counted as a sale and pays the secondary seller',()=>{const {pixel,market,event,n,maker,buyer,get}=harness();pixel.handleTransfer(event({tokenId:n(1),from:maker,to:buyer}));market.handleOfferMade(event({offerId:n(1),tokenId:n(1),bidder:maker,amount:n(10000),expiry:n(2000)}));pixel.handleTransfer(event({tokenId:n(1),from:buyer,to:maker}));market.handleOfferAccepted(event({offerId:n(1),tokenId:n(1),seller:buyer,buyer:maker,amount:n(10000),royalty:n(100),fee:n(100)}));assert.equal(get('Offer','1').status,'ACCEPTED');assert.equal(get('Account',buyer.toHexString()).credits.toString(),'9800');assert.equal(get('Stats','global').sales.toString(),'1');assert.equal(get('Stats','global').royalties.toString(),'100');});
test('marketplace approval revocation and reapproval retain reversible listing history',()=>{const {pixel,market,event,n,maker,buyer,get,Address}=harness(),operator=Address.fromString(deployment.PixelMarket.address);market.handleListed(event({tokenId:n(1),listingId:n(1),seller:maker,price:n(10000),expiry:n(2000),nonce:n(1)}));pixel.handleApprovalForAll(event({owner:maker,operator,approved:true}));assert.equal(get('MarketApproval',maker.toHexString()).approved,true);pixel.handleApprovalForAll(event({owner:maker,operator,approved:false}));assert.equal(get('MarketApproval',maker.toHexString()).approved,false);assert.equal(get('Listing','1').status,'ACTIVE');pixel.handleApprovalForAll(event({owner:maker,operator:buyer,approved:true}));assert.equal(get('MarketApproval',maker.toHexString()).approved,false);pixel.handleApproval(event({tokenId:n(1),owner:maker,approved:operator}));assert.equal(get('Pixel','1').tokenApproved,true);pixel.handleTransfer(event({tokenId:n(1),from:maker,to:maker}));assert.equal(get('Pixel','1').tokenApproved,false);assert.equal(get('Pixel','1').listing,'1');pixel.handleApprovalForAll(event({owner:maker,operator,approved:true}));assert.equal(get('MarketApproval',maker.toHexString()).approved,true);pixel.handleTransfer(event({tokenId:n(1),from:maker,to:buyer}));assert.equal(get('Pixel','1').ownerApproval,buyer.toHexString());assert.equal(get('MarketApproval',buyer.toHexString()).approved,false);assert.equal(get('Listing','1').status,'INVALIDATED');});
test('zero-value withdrawal and shared recipient credits do not alter volume',()=>{const {market,event,n,maker,buyer,get,Address}=harness(),recipient=Address.fromString(deployment.deployer);market.handleOfferMade(event({offerId:n(1),tokenId:n(1),bidder:buyer,amount:n(5000),expiry:n(2000)}));market.handleOfferCancelled(event({offerId:n(1)}));market.handleWithdrawn(event({account:buyer,recipient,amount:n(5000)}));assert.equal(get('Account',buyer.toHexString()).credits.toString(),'0');assert.equal(get('Stats','global').sales.toString(),'0');assert.equal(get('Stats','global').volume.toString(),'0');});
