export const lendingPoolAbi = [
  {
    type: "function", name: "collateralConfigs", stateMutability: "view",
    inputs: [{ name: "asset", type: "address" }],
    outputs: [
      { name: "oracle", type: "address" }, { name: "supplyCap", type: "uint256" },
      { name: "loanToValueBps", type: "uint16" }, { name: "liquidationThresholdBps", type: "uint16" },
      { name: "liquidationBonusBps", type: "uint16" }, { name: "decimals", type: "uint8" }, { name: "enabled", type: "bool" },
      { name: "marginCallThresholdBps", type: "uint16" },
    ],
  },
  {
    type: "function",
    name: "IMPLEMENTATION_ID",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "totalSupplied",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalBorrowed",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "availableLiquidity",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "supplyRate",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "rateWad", type: "uint256" }],
  },
  {
    type: "function",
    name: "borrowRate",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "rateWad", type: "uint256" }],
  },
  {
    type: "function",
    name: "lenderRate",
    stateMutability: "pure",
    inputs: [],
    outputs: [{ name: "rateWad", type: "uint256" }],
  },
  {
    type: "function",
    name: "protocolRate",
    stateMutability: "pure",
    inputs: [],
    outputs: [{ name: "rateWad", type: "uint256" }],
  },
  {
    type: "function",
    name: "supplyBalance",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "maxWithdraw",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "debtBalance",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "healthFactor",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "healthFactorWad", type: "uint256" }],
  },
  {
    type: "function",
    name: "accountRisk",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [
      { name: "collateralValueNusd", type: "uint256" },
      { name: "borrowingCapacityNusd", type: "uint256" },
      { name: "marginCallCapacityNusd", type: "uint256" },
      { name: "liquidationCapacityNusd", type: "uint256" },
      { name: "debtNusd", type: "uint256" },
      { name: "currentLtvBps", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "maxBorrow",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "amountNusd", type: "uint256" }],
  },
  {
    type: "function",
    name: "maxWithdrawCollateral",
    stateMutability: "view",
    inputs: [
      { name: "account", type: "address" },
      { name: "asset", type: "address" },
    ],
    outputs: [{ name: "amount", type: "uint256" }],
  },
  {
    type: "function",
    name: "collateralBalance",
    stateMutability: "view",
    inputs: [
      { name: "account", type: "address" },
      { name: "asset", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "supply",
    stateMutability: "nonpayable",
    inputs: [
      { name: "amount", type: "uint256" },
      { name: "onBehalfOf", type: "address" },
    ],
    outputs: [{ name: "shares", type: "uint256" }],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [
      { name: "amount", type: "uint256" },
      { name: "recipient", type: "address" },
    ],
    outputs: [{ name: "assets", type: "uint256" }],
  },
  {
    type: "function",
    name: "depositCollateral",
    stateMutability: "nonpayable",
    inputs: [
      { name: "asset", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "onBehalfOf", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "withdrawCollateral",
    stateMutability: "nonpayable",
    inputs: [
      { name: "asset", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "recipient", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "borrow",
    stateMutability: "nonpayable",
    inputs: [
      { name: "amount", type: "uint256" },
      { name: "recipient", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "repay",
    stateMutability: "nonpayable",
    inputs: [
      { name: "amount", type: "uint256" },
      { name: "onBehalfOf", type: "address" },
    ],
    outputs: [{ name: "repaid", type: "uint256" }],
  },
] as const;
