// SPDX-License-Identifier: MIT
// Digest builder sanity: determinism, domain binding, call-order sensitivity.
// (Byte-level agreement with the Solidity wallet is proven on-chain via the
// vectors generated by vectors.gen.ts and the anvil integration script.)

import assert from "node:assert/strict";
import test from "node:test";
import {
  callHash,
  callsHash,
  domainSeparator,
  messageDigest,
  opDigest,
  rotateDigest,
} from "../src/digest.ts";
import { keccak } from "../src/crypto.ts";
import type { QWalletOp } from "../src/encode.ts";

const WALLET = "0x1111111111111111111111111111111111111111";
const OTHER_WALLET = "0x2222222222222222222222222222222222222222";
const DOMAIN = { chainId: 4441n, wallet: WALLET };
const RECIPIENT = "0x3333333333333333333333333333333333333333";

function op(calls: QWalletOp["calls"], nonce = 0n, validUntil = 1_800_000_000n): QWalletOp {
  return { walletNonce: nonce, validUntil, calls };
}

const transferCall = { to: RECIPIENT, value: 1_000_000n, data: "0x" as `0x${string}` };
const erc20Call = {
  to: "0x4444444444444444444444444444444444444444",
  value: 0n,
  data: "0xa9059cbb00000000000000000000000033333333333333333333333333333333333333330000000000000000000000000000000000000000000000000000000000000001" as `0x${string}`,
};

test("domainSeparator binds chain and wallet", () => {
  const d1 = domainSeparator(DOMAIN);
  const d2 = domainSeparator({ chainId: 4442n, wallet: WALLET });
  const d3 = domainSeparator({ chainId: 4441n, wallet: OTHER_WALLET });
  assert.equal(d1.length, 32);
  assert.notDeepEqual(Buffer.from(d1), Buffer.from(d2));
  assert.notDeepEqual(Buffer.from(d1), Buffer.from(d3));
});

test("opDigest is deterministic and nonce/deadline sensitive", () => {
  const o = op([transferCall], 0n, 1_700_000_000n);
  const a = opDigest(o, DOMAIN);
  const b = opDigest(o, DOMAIN);
  assert.deepEqual(Buffer.from(a), Buffer.from(b), "deterministic");
  const c = opDigest({ ...o, walletNonce: 1n }, DOMAIN);
  assert.notDeepEqual(Buffer.from(a), Buffer.from(c), "nonce in digest");
  const d = opDigest({ ...o, validUntil: 2_000_000_000n }, DOMAIN);
  assert.notDeepEqual(Buffer.from(a), Buffer.from(d), "deadline in digest");
});

test("call order and contents bind the digest", () => {
  const o1 = op([transferCall, erc20Call]);
  const o2 = op([erc20Call, transferCall]);
  assert.notDeepEqual(Buffer.from(opDigest(o1, DOMAIN)), Buffer.from(opDigest(o2, DOMAIN)));
  const o3 = op([transferCall]);
  assert.notDeepEqual(Buffer.from(opDigest(o1, DOMAIN)), Buffer.from(opDigest(o3, DOMAIN)));
});

test("same underlying calldata but different receiver gives different callHash", () => {
  const c1 = callHash({ to: RECIPIENT, value: 0n, data: "0x00" as `0x${string}` });
  const c2 = callHash({ to: OTHER_WALLET, value: 0n, data: "0x00" as `0x${string}` });
  assert.notDeepEqual(Buffer.from(c1), Buffer.from(c2));
});

test("callsHash stable and equals keccak(concat of call hashes)", () => {
  const calls = [transferCall, erc20Call];
  const parts = calls.map(callHash);
  let expected = new Uint8Array(0);
  for (const p of parts) {
    const next = new Uint8Array(expected.length + p.length);
    next.set(expected, 0);
    next.set(p, expected.length);
    expected = next;
  }
  const manual = keccak(expected);
  assert.deepEqual(Buffer.from(callsHash(calls)), Buffer.from(manual));
});

test("rotate/message digests are domain-bound and deterministic", () => {
  const newRoot = keccak(new TextEncoder().encode("new tree root"));
  const r1 = rotateDigest(newRoot, 1, DOMAIN);
  const r2 = rotateDigest(newRoot, 1, DOMAIN);
  assert.deepEqual(Buffer.from(r1), Buffer.from(r2));
  const r3 = rotateDigest(newRoot, 2, DOMAIN);
  assert.notDeepEqual(Buffer.from(r1), Buffer.from(r3), "nextEpoch in digest");

  const mh = keccak(new TextEncoder().encode("msg"));
  const m1 = messageDigest(mh, DOMAIN);
  assert.deepEqual(Buffer.from(m1), Buffer.from(messageDigest(mh, DOMAIN)));
  assert.deepEqual(Buffer.from(m1), Buffer.from(m1));
});

test("rotate root digest differs from an execute digest", () => {
  const newRoot = keccak(new TextEncoder().encode("root"));
  const r = rotateDigest(newRoot, 1, DOMAIN);
  const o = opDigest(op([], 0n), DOMAIN);
  assert.notDeepEqual(Buffer.from(r), Buffer.from(o), "tag separation");
});
