// SPDX-License-Identifier: MIT
// Canonical SDK -> Solidity vectors. Run once (and on every parameter change):
//
//   npm run vectors
//
// It writes:
//   contracts/test/vectors/HashSigVectors.data.sol   (replayed by forge)
//   sdk/test/vectors/reference.json                  (locked for TS regression)
//
// Every vector is a (digest, leafIndex) signed by the SDK signer; forge replays
// it through HashSig.leafFromSignature + computeRoot and must reproduce the same
// expectedLeaf and root. This is the byte-level cross-language proof between
// quantum-wallet/sdk (TypeScript) and quantum-wallet/contracts (Solidity).

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { keccak, toHex, utf8 } from "../src/crypto.ts";
import { QuantumSigner } from "../src/signer.ts";
import { publicLeaf } from "../src/wots.ts";
import { LEN, TREE_H } from "../src/constants.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");

export interface Vector {
  digest: string;
  leafIndex: number;
  expectedLeaf: string;
  root: string;
  wots: string[];
  path: string[];
}

export function generateVectors(): { seed: string; vectors: Vector[] } {
  const seed = keccak(utf8("0xQ-vector-seed-v1"));
  const signer = new QuantumSigner(seed);
  const digest1 = keccak(utf8("vector digest 1"));
  const digest2 = keccak(utf8("vector digest 2 — checksum edge: 0xFFFF nibbles"));
  const digest3 = keccak(new Uint8Array(32).fill(0xff));

  const leaves = [0, 1, 2, 5, 511, 1023];
  const vectors: Vector[] = [];
  for (const idx of leaves) {
    // Alternate digests so multiple leaves per digest are covered.
    const digest = idx % 2 === 0 ? digest1 : digest2;
    if (idx === 1023) {
      const last = new QuantumSigner(seed); // re-derived for clarity; identical tree
      const s = last.signAt(digest3, idx);
      vectors.push({
        digest: toHex(digest3),
        leafIndex: idx,
        expectedLeaf: toHex(publicLeaf(seed, idx)),
        root: toHex(signer.root),
        wots: s.wots.map(toHex),
        path: s.path.map(toHex),
      });
      continue;
    }
    const s = signer.signAt(digest, idx);
    vectors.push({
      digest: toHex(digest),
      leafIndex: idx,
      expectedLeaf: toHex(publicLeaf(seed, idx)),
      root: toHex(signer.root),
      wots: s.wots.map(toHex),
      path: s.path.map(toHex),
    });
  }
  // Also a rotated tree (epoch change keeps the SAME address, new root).
  const seed2 = keccak(utf8("0xQ-vector-seed-v2"));
  const signer2 = new QuantumSigner(seed2);
  const s2 = signer2.signAt(digest1, 3);
  vectors.push({
    digest: toHex(digest1),
    leafIndex: 3,
    expectedLeaf: toHex(publicLeaf(seed2, 3)),
    root: toHex(signer2.root),
    wots: s2.wots.map(toHex),
    path: s2.path.map(toHex),
  });

  return { seed: toHex(seed), vectors };
}

function hex32(h: string): string {
  if (h.length !== 66 || !h.startsWith("0x")) throw new Error("not a bytes32 hex");
  return h;
}

export function toSolidityFile(seed: string, vectors: Vector[]): string {
  const lines: string[] = [];
  for (let i = 0; i < vectors.length; i++) {
    const v = vectors[i];
    const wotsList = v.wots
      .map((w) => `            bytes32(${hex32(w)})`)
      .join(",\n");
    const pathList = v.path
      .map((p) => `            bytes32(${hex32(p)})`)
      .join(",\n");
    lines.push(
      `    out[${i}] = SdkVector({\n` +
        `        digest: bytes32(${hex32(v.digest)}),\n` +
        `        leafIndex: ${v.leafIndex},\n` +
        `        expectedLeaf: bytes32(${hex32(v.expectedLeaf)}),\n` +
        `        root: bytes32(${hex32(v.root)}),\n` +
        `        wots: [\n${wotsList}\n        ],\n` +
        `        path: [\n${pathList}\n        ]\n` +
        `    });`,
    );
  }
  return (
    `// SPDX-License-Identifier: MIT\n` +
    `// GENERATED by quantum-wallet/sdk/test/vectors.gen.ts — DO NOT EDIT.\n` +
    `// Regenerate with: cd quantum-wallet/sdk && npm run vectors\n` +
    `pragma solidity ^0.8.24;\n\n` +
    `struct SdkVector {\n` +
    `    bytes32 digest;\n` +
    `    uint32 leafIndex;\n` +
    `    bytes32 expectedLeaf;\n` +
    `    bytes32 root;\n` +
    `    bytes32[${LEN}] wots;\n` +
    `    bytes32[${TREE_H}] path;\n` +
    `}\n\n` +
    `library SdkVectors {\n` +
    `    function all() internal pure returns (SdkVector[] memory out) {\n` +
    `        out = new SdkVector[](${vectors.length});\n` +
    lines.join("\n\n") +
    `\n    }\n` +
    `}\n`
  );
}

function main() {
  const { seed, vectors } = generateVectors();

  const solDir = join(ROOT, "contracts", "test", "vectors");
  mkdirSync(solDir, { recursive: true });
  writeFileSync(join(solDir, "HashSigVectors.data.sol"), toSolidityFile(seed, vectors));

  const jsonDir = join(HERE, "vectors");
  mkdirSync(jsonDir, { recursive: true });
  writeFileSync(
    join(jsonDir, "reference.json"),
    JSON.stringify({ seed, vectors, generatedBy: "vectors.gen.ts", constants: { LEN, TREE_H } }, null, 2),
  );

  console.log(`wrote ${vectors.length} vectors`);
  console.log("  -> contracts/test/vectors/HashSigVectors.data.sol");
  console.log("  -> sdk/test/vectors/reference.json");
}

if (process.argv[1] && process.argv[1].endsWith("vectors.gen.ts")) {
  main();
}
