import {Address,BigInt,Bytes} from '@graphprotocol/graph-ts';
import {Listed,ListingCancelled,Sold,OfferMade,OfferCancelled,OfferAccepted,Withdrawn} from '../generated/PixelMarket/PixelMarket';
import {Pixel,Listing,Offer,Sale,Account} from '../generated/schema';
import {ZERO,stats,activity,credit} from './shared';
import {FEE_RECIPIENT} from './config';
export function handleListed(event:Listed):void {const p=Pixel.load(event.params.tokenId.toString());if(!p)return;if(p.listing!=null){const previous=Listing.load(p.listing!);if(previous){previous.status='REPLACED';previous.save();}}const l=new Listing(event.params.listingId.toString());l.pixel=p.id;l.seller=event.params.seller;l.price=event.params.price;l.expiry=event.params.expiry;l.nonce=event.params.nonce;l.createdAt=event.block.timestamp;l.status='ACTIVE';l.save();p.listing=l.id;p.save();activity(event,'Listed',event.params.tokenId,event.params.seller,event.params.price);}
export function handleListingCancelled(event:ListingCancelled):void {const l=Listing.load(event.params.listingId.toString());if(l){l.status='CANCELLED';l.save();}const p=Pixel.load(event.params.tokenId.toString());if(p&&p.listing==event.params.listingId.toString()){p.listing=null;p.save();}activity(event,'ListingCancelled',event.params.tokenId,event.transaction.from,ZERO);}
function sale(id:string,pixel:string,seller:Address,buyer:Address,price:BigInt,royalty:BigInt,fee:BigInt,kind:string,transaction:Bytes,timestamp:BigInt,feeRecipient:Address):void {
 const p=Pixel.load(pixel);if(!p)return;const s=new Sale(id);s.pixel=pixel;s.seller=seller;s.buyer=buyer;s.price=price;s.royalty=royalty;s.fee=fee;s.kind=kind;s.transaction=transaction;s.timestamp=timestamp;s.save();credit(seller,price.minus(royalty).minus(fee));credit(Address.fromBytes(p.creator),royalty);credit(feeRecipient,fee);const st=stats();st.sales=st.sales.plus(BigInt.fromI32(1));st.volume=st.volume.plus(price);st.royalties=st.royalties.plus(royalty);st.fees=st.fees.plus(fee);st.save();
}
export function handleSold(event:Sold):void {const l=Listing.load(event.params.listingId.toString());if(l){l.status='SOLD';l.save();}sale(event.transaction.hash.toHexString()+'-'+event.logIndex.toString(),event.params.tokenId.toString(),event.params.seller,event.params.buyer,event.params.price,event.params.royalty,event.params.fee,'FIXED_PRICE',event.transaction.hash,event.block.timestamp,Address.fromString(FEE_RECIPIENT));activity(event,'Sold',event.params.tokenId,event.params.buyer,event.params.price);}
export function handleOfferMade(event:OfferMade):void {const o=new Offer(event.params.offerId.toString());o.pixel=event.params.tokenId.toString();o.bidder=event.params.bidder;o.amount=event.params.amount;o.expiry=event.params.expiry;o.status='OPEN';o.createdAt=event.block.timestamp;o.save();activity(event,'OfferMade',event.params.tokenId,event.params.bidder,event.params.amount);}
export function handleOfferCancelled(event:OfferCancelled):void {const o=Offer.load(event.params.offerId.toString());if(!o)return;o.status='CANCELLED';o.save();credit(Address.fromBytes(o.bidder),o.amount);activity(event,'OfferCancelled',BigInt.fromString(o.pixel),Address.fromBytes(o.bidder),o.amount);}
export function handleOfferAccepted(event:OfferAccepted):void {const o=Offer.load(event.params.offerId.toString());if(o){o.status='ACCEPTED';o.save();}sale(event.transaction.hash.toHexString()+'-'+event.logIndex.toString(),event.params.tokenId.toString(),event.params.seller,event.params.buyer,event.params.amount,event.params.royalty,event.params.fee,'OFFER',event.transaction.hash,event.block.timestamp,Address.fromString(FEE_RECIPIENT));activity(event,'OfferAccepted',event.params.tokenId,event.params.buyer,event.params.amount);}
export function handleWithdrawn(event:Withdrawn):void {const a=Account.load(event.params.account.toHexString());if(a){a.credits=a.credits.minus(event.params.amount);a.save();}activity(event,'Withdrawn',ZERO,event.params.account,event.params.amount);}

