// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {HashSig} from "../../src/libs/HashSig.sol";

/// @title TreeSigner — SOLIDITY-side reimplementation of the SDK signer, used ONLY
/// in tests to produce genuine signatures that QuantumWallet must accept. It must
/// match `sdk/src/wots.ts` + `sdk/src/merkle.ts` byte-for-byte:
///
///   sk_{i,j} = keccak256(abi.encodePacked(seed, uint16(i), uint8(j)))
///   leaf_i   = keccak( concat_{j=0..66} chain(sk_{i,j}, j, PUB_STEPS) )
///   root     = Merkle(keccak(left||right)) over leaves 0..TREE_N-1
///   sig_j    = chain(sk_{i,j}, j, PUB_STEPS - digit_j(digest))
///
/// The real cross-language proof lives in HashSigVectors.t.sol, which replays
/// digests/signatures generated by the TypeScript SDK on-chain.
contract TreeSigner {
    bytes32 private immutable _seed;
    bytes32[][] private _tree; // _tree[level][node]

    constructor(bytes32 seed_) {
        _seed = seed_;
        _build();
    }

    function seed() external view returns (bytes32) {
        return _seed;
    }

    function root() external view returns (bytes32) {
        return _tree[_tree.length - 1][0];
    }

    /// Deterministic chain secret for leaf `i`, chain `j`.
    function chainSecret(uint32 i, uint8 j) public view returns (bytes32) {
        return keccak256(abi.encodePacked(_seed, uint16(i), j));
    }

    function leafPublic(uint32 i) public view returns (bytes32) {
        bytes32[] memory pks = new bytes32[](HashSig.LEN);
        for (uint8 j = 0; j < HashSig.LEN; ++j) {
            pks[j] = HashSig.publicElement(chainSecret(i, j), j);
        }
        return keccak256(abi.encodePacked(pks));
    }

    /// WOTS signature over `digest` for leaf `i`, plus its auth path.
    function sign(uint32 i, bytes32 digest)
        external
        view
        returns (bytes32[] memory wots, bytes32[] memory path)
    {
        // Message digits + checksum are recomputed nibble-by-nibble exactly as
        // HashSig.messageDigits/checksumDigits would (shift by (252 - 4j), then
        // base-16 of the checksum sum). This avoids fixed-array LOCALS sized by
        // `HashSig.LEN1`/`HashSig.LEN2` — member-access constants cannot appear
        // as a fixed-array *type* size (parser error), only as `new` lengths.
        uint256 d = uint256(digest);
        uint256 sum;
        wots = new bytes32[](HashSig.LEN);
        for (uint256 j = 0; j < HashSig.LEN1; ++j) {
            uint256 digit = (d >> (252 - 4 * j)) & 0xF;
            sum += HashSig.PUB_STEPS - digit;
            wots[j] = HashSig.signElement(chainSecret(i, uint8(j)), uint8(j), uint8(digit));
        }
        for (uint256 j = 0; j < HashSig.LEN2; ++j) {
            uint256 chainIdx = HashSig.LEN1 + j;
            uint8 cs = uint8((sum >> (4 * (HashSig.LEN2 - 1 - j))) & 0xF);
            wots[chainIdx] = HashSig.signElement(chainSecret(i, uint8(chainIdx)), uint8(chainIdx), cs);
        }

        path = new bytes32[](HashSig.TREE_H);
        for (uint256 level = 0; level < HashSig.TREE_H; ++level) {
            uint256 nodeIndex = i >> level;
            path[level] = _tree[level][nodeIndex ^ 1];
        }
    }

    function _build() internal {
        uint32 n = uint32(HashSig.TREE_N);
        bytes32[] memory level = new bytes32[](n);
        for (uint32 i = 0; i < n; ++i) {
            bytes32[] memory pks = new bytes32[](HashSig.LEN);
            for (uint8 j = 0; j < HashSig.LEN; ++j) {
                pks[j] = HashSig.publicElement(chainSecret(i, j), j);
            }
            level[i] = keccak256(abi.encodePacked(pks));
        }
        _tree.push(level);

        while (level.length > 1) {
            uint256 half = level.length / 2;
            bytes32[] memory next = new bytes32[](half);
            for (uint256 k = 0; k < half; ++k) {
                next[k] = keccak256(abi.encodePacked(level[2 * k], level[2 * k + 1]));
            }
            _tree.push(next);
            level = next;
        }
    }
}
