export const nusdPointsStakingAbi = [
  { type: "function", name: "nusd", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { type: "function", name: "owner", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { type: "function", name: "guardian", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { type: "function", name: "redemptionSigner", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { type: "function", name: "stakingPaused", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "bool" }] },
  { type: "function", name: "redemptionsPaused", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "bool" }] },
  { type: "function", name: "redemptionEnabled", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "bool" }] },
  { type: "function", name: "nusdPerXPointWad", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "rateVersion", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "redemptionReserve", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "excessNusd", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "totalLocked", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "totalLockedByUser", stateMutability: "view", inputs: [{ name: "account", type: "address" }], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "earnedPointCredits", stateMutability: "view", inputs: [{ name: "account", type: "address" }], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "spentPointCredits", stateMutability: "view", inputs: [{ name: "account", type: "address" }], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "availablePointCredits", stateMutability: "view", inputs: [{ name: "account", type: "address" }], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "redemptionNonces", stateMutability: "view", inputs: [{ name: "account", type: "address" }], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "userPositionCount", stateMutability: "view", inputs: [{ name: "account", type: "address" }], outputs: [{ name: "", type: "uint256" }] },
  {
    type: "function",
    name: "userPositionIds",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }, { name: "offset", type: "uint256" }, { name: "limit", type: "uint256" }],
    outputs: [{ name: "ids", type: "uint256[]" }],
  },
  {
    type: "function",
    name: "getPosition",
    stateMutability: "view",
    inputs: [{ name: "positionId", type: "uint256" }],
    outputs: [{
      name: "",
      type: "tuple",
      components: [
        { name: "account", type: "address" },
        { name: "amount", type: "uint256" },
        { name: "pointCredits", type: "uint256" },
        { name: "unlockTime", type: "uint64" },
        { name: "lockDuration", type: "uint32" },
        { name: "withdrawn", type: "bool" },
      ],
    }],
  },
  { type: "function", name: "quoteRedemption", stateMutability: "view", inputs: [{ name: "pointCredits", type: "uint256" }], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "isSolvent", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "bool" }] },
  {
    type: "function",
    name: "stake",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }, { name: "lockDuration", type: "uint32" }],
    outputs: [{ name: "positionId", type: "uint256" }],
  },
  { type: "function", name: "withdraw", stateMutability: "nonpayable", inputs: [{ name: "positionId", type: "uint256" }], outputs: [] },
  { type: "function", name: "redeemPoints", stateMutability: "nonpayable", inputs: [{ name: "pointCredits", type: "uint256" }], outputs: [{ name: "nusdOut", type: "uint256" }] },
  { type: "function", name: "fundRedemptionReserve", stateMutability: "nonpayable", inputs: [{ name: "amount", type: "uint256" }], outputs: [] },
  { type: "function", name: "withdrawRedemptionReserve", stateMutability: "nonpayable", inputs: [{ name: "recipient", type: "address" }, { name: "amount", type: "uint256" }], outputs: [] },
  { type: "function", name: "withdrawExcess", stateMutability: "nonpayable", inputs: [{ name: "recipient", type: "address" }, { name: "amount", type: "uint256" }], outputs: [] },
  { type: "function", name: "configureRedemption", stateMutability: "nonpayable", inputs: [{ name: "newNusdPerXPointWad", type: "uint256" }, { name: "enabled", type: "bool" }], outputs: [] },
  { type: "function", name: "setRedemptionSigner", stateMutability: "nonpayable", inputs: [{ name: "newSigner", type: "address" }], outputs: [] },
  { type: "function", name: "setGuardian", stateMutability: "nonpayable", inputs: [{ name: "newGuardian", type: "address" }], outputs: [] },
  { type: "function", name: "pauseStaking", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "unpauseStaking", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "pauseRedemptions", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "unpauseRedemptions", stateMutability: "nonpayable", inputs: [], outputs: [] },
  {
    type: "function",
    name: "redeem",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "voucher",
        type: "tuple",
        components: [
          { name: "account", type: "address" },
          { name: "recipient", type: "address" },
          { name: "pointCredits", type: "uint256" },
          { name: "nonce", type: "uint256" },
          { name: "deadline", type: "uint256" },
          { name: "rateVersion", type: "uint256" },
        ],
      },
      { name: "signature", type: "bytes" },
    ],
    outputs: [{ name: "nusdOut", type: "uint256" }],
  },
] as const;

export { POINTS_PER_XPOINT } from "../points";

export const pointsLockOptions = [
  { days: 30, duration: 30 * 24 * 60 * 60, multiplierBps: 10_000, label: "30 days", multiplier: "x1" },
  { days: 90, duration: 90 * 24 * 60 * 60, multiplierBps: 12_000, label: "90 days", multiplier: "x1.2" },
  { days: 180, duration: 180 * 24 * 60 * 60, multiplierBps: 15_000, label: "180 days", multiplier: "x1.5" },
  { days: 365, duration: 365 * 24 * 60 * 60, multiplierBps: 30_000, label: "365 days", multiplier: "x3" },
] as const;
