import { parseAbi } from "viem";

export const zeroXPumpAbi = parseAbi([
  "function reserveMarket(bytes32 contentHash)",
  "function creationReservations(address owner,bytes32 contentHash) view returns (bool)",
  "function createdTokenByContentHash(address owner,bytes32 contentHash) view returns (address token)",
  "function createMarket(string name,string symbol,string metadataURI,string imageURI,bytes32 contentHash) returns (address token)",
  "function buy(address token,uint256 maxNusdIn,uint256 minTokenOut,uint256 deadline) returns (uint256 tokenOut,uint256 userNusdAmount)",
  "function sell(address token,uint256 tokenIn,uint256 minNusdOut,uint256 deadline) returns (uint256 userNusdAmount)",
  "function quoteBuy(address token,uint256 maxNusdIn) view returns (uint256 tokenOut,uint256 curveNusdAmount,uint256 userNusdAmount,uint256 feeNusd,bool readyAfter)",
  "function quoteSell(address token,uint256 tokenIn) view returns (uint256 curveNusdAmount,uint256 userNusdAmount,uint256 feeNusd)",
  "function markets(address token) view returns (address creator,uint256 tokenReserve,uint256 realNusdReserve,uint256 virtualTokenReserve,uint256 virtualNusdReserve,uint256 totalNusdVolume,uint64 createdAt,uint8 lifecycle,address dex,bytes32 dexPairId,address pool)",
  "function status(address token) view returns (uint8)",
  "function spotPriceNusdWad(address token) view returns (uint256)",
  "function curveProgressBps(address token) view returns (uint256)",
  "function graduationThresholdNusd() view returns (uint256)",
  "function graduationReserveThresholdNusd() view returns (uint256)",
  "function createFee() pure returns (uint256)",
  "function tradeFeeBps() pure returns (uint256)",
  "function nusd() view returns (address)",
  "function vault() view returns (address)",
  "function paused() view returns (bool)",
  "function admin() view returns (address)",
  "function accruedProtocolFeesNusd() view returns (uint256)",
  "function withdrawProtocolFees(address recipient,uint256 amountNusd)",
  "function totalMarkets() view returns (uint256)",
  "function getAllTokens() view returns (address[])",
  "function getTokensByCreator(address creator) view returns (address[])",
  "event TokenCreated(address indexed token,address indexed creator,bytes32 indexed contentHash,string name,string symbol,string metadataURI,string imageURI,uint256 totalSupply,uint256 curveTokenSupply,uint256 virtualNusdReserve,uint256 virtualTokenReserve,uint256 graduationThresholdNusd,uint256 graduationReserveThresholdNusd,uint256 creationFeeNusd)",
  "event CreationFeePaid(address indexed owner,bytes32 indexed contentHash,uint256 creationFeeNusd)",
  "event TokenTraded(address indexed token,address indexed trader,bool indexed isBuy,uint256 tokenAmount,uint256 curveNusdAmount,uint256 userNusdAmount,uint256 feeNusd,uint256 realNusdReserveAfter,uint256 tokenReserveAfter,uint256 virtualNusdReserveAfter,uint256 virtualTokenReserveAfter,uint256 circulatingSupplyAfter,uint256 spotPriceNusdWad,uint256 curveProgressBps)",
  "event TokenReadyForGraduation(address indexed token,uint256 realNusdReserve,uint256 tokenReserve,uint256 thresholdNusd)",
  "event TokenCurveReopened(address indexed token,uint256 realNusdReserve,uint256 tokenReserve)",
  "event TokenGraduated(address indexed token,address indexed dex,bytes32 indexed pairId,address pool,uint256 nusdLiquidity,uint256 tokenLiquidity,uint256 lpAmount,address lpRecipient)",
  "event ProtocolFeesWithdrawn(address indexed recipient,uint256 amountNusd)",
]);

export const pumpTokenAbi = parseAbi([
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address account) view returns (uint256)",
  "function allowance(address owner,address spender) view returns (uint256)",
  "function approve(address spender,uint256 amount) returns (bool)",
  "function metadataURI() view returns (string)",
  "function imageURI() view returns (string)",
]);

export const nusdAbi = parseAbi([
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function vault() view returns (address)",
  "function oracle() view returns (address)",
  "function supplyCeilingNusd() view returns (uint256)",
  "function totalCollateralWei() view returns (uint256)",
  "function reserveValueNusd() view returns (uint256)",
  "function mintPaused() view returns (bool)",
  "function redeemPaused() view returns (bool)",
  "function quoteMint(uint256 collateralWei) view returns (uint256 amountNusd)",
  "function mintAtOracle(uint256 minNusdOut,address recipient) payable returns (uint256 amountNusd)",
  "function quoteRedeem(uint256 amountNusd) view returns (uint256 collateralOutWei)",
  "function redeemAtOracle(uint256 amountNusd,uint256 minCollateralOutWei,address recipient) returns (uint256 collateralOutWei)",
  "function balanceOf(address account) view returns (uint256)",
  "function allowance(address owner,address spender) view returns (uint256)",
  "function approve(address spender,uint256 amount) returns (bool)",
  "function transfer(address to,uint256 amount) returns (bool)",
  "event MintedAtOracle(address indexed payer,address indexed recipient,uint256 collateralInWei,uint256 amountNusd)",
  "event RedeemedAtOracle(address indexed account,address indexed recipient,uint256 amountNusd,uint256 collateralOutWei)",
]);

export const diaOracleAdapterAbi = parseAbi([
  "function readPriceWad() view returns (uint256 priceWad,uint256 updatedAt,uint80 roundId)",
  "function isFresh() view returns (bool)",
  "function maxPriceAge() view returns (uint256)",
]);
