import { readFileSync, writeFileSync } from "node:fs";
const root = new URL("../", import.meta.url);
const artifact = JSON.parse(readFileSync(new URL("contracts/out/RwaMarket.sol/RwaMarket.json", root), "utf8"));
const oracle = JSON.parse(readFileSync(new URL("contracts/out/RwaPriceOracle.sol/RwaPriceOracle.json", root), "utf8"));
const content = `// Generated by 0xFi/scripts/generate-rwa-abi.mjs after forge build.\nexport const rwaMarketAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;\nexport const rwaOracleAbi = ${JSON.stringify(oracle.abi, null, 2)} as const;\n`;
writeFileSync(new URL("../shared/rwa/abi.ts", root), content);
